# Generated by Django 5.0 on 2023-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(max_length=1000)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("tags", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "OPEN"),
                            ("WORKING", "Working"),
                            ("DONE", "Done"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="OPEN",
                        max_length=7,
                    ),
                ),
            ],
        ),
    ]
